-- MySQL Script generated by MySQL Workbench
-- Wed Apr  3 12:03:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DONVI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DONVI` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tendonvi` VARCHAR(45) NULL,
  `nguoidungdau` VARCHAR(45) NULL,
  `diachidonvi` VARCHAR(45) NULL,
  `dienthoai` VARCHAR(45) NULL,
  `website` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CBGV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CBGV` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hoten` VARCHAR(45) NULL,
  `matkhau` VARCHAR(45) NULL,
  `ngaysinh` DATETIME NULL,
  `gioitinh` VARCHAR(45) NULL,
  `hocham` VARCHAR(45) NULL,
  `hocvi` VARCHAR(45) NULL,
  `namduocphong` DATETIME NULL,
  `namdathocvi` DATETIME NULL,
  `chucdanhnc` VARCHAR(45) NULL,
  `dienthoaiNR` VARCHAR(45) NULL,
  `CQ` VARCHAR(45) NULL,
  `mobile` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `linhvucchuyenmonsau` VARCHAR(45) NULL,
  `createddate` TIMESTAMP not NULL,
  `DONVI_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CBGV_DONVI1_idx` (`DONVI_id` ASC) VISIBLE,
  CONSTRAINT `fk_CBGV_DONVI1`
    FOREIGN KEY (`DONVI_id`)
    REFERENCES `mydb`.`DONVI` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LINHVUC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LINHVUC` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `malinhvuc` VARCHAR(45) NULL,
  `tengoi` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NGANH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NGANH` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manganh` VARCHAR(45) NULL,
  `tengoi` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CHUYENNGANH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CHUYENNGANH` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `machuyennganh` VARCHAR(45) NULL,
  `tengoi` VARCHAR(45) NULL,
  `NGANH_id` INT NULL,
  `CBGV_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CHUYENNGANH_NGANH1_idx` (`NGANH_id` ASC) VISIBLE,
  INDEX `fk_CHUYENNGANH_CBGV1_idx` (`CBGV_id` ASC) VISIBLE,
  CONSTRAINT `fk_CHUYENNGANH_NGANH1`
    FOREIGN KEY (`NGANH_id`)
    REFERENCES `mydb`.`NGANH` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CHUYENNGANH_CBGV1`
    FOREIGN KEY (`CBGV_id`)
    REFERENCES `mydb`.`CBGV` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KINHNGHIEMKHCN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KINHNGHIEMKHCN` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hinhthuchoidong` VARCHAR(45) NULL,
  `solan` VARCHAR(45) NULL,
  `CBGV_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_KINHNGHIEMKHCN_CBGV1_idx` (`CBGV_id` ASC) VISIBLE,
  CONSTRAINT `fk_KINHNGHIEMKHCN_CBGV1`
    FOREIGN KEY (`CBGV_id`)
    REFERENCES `mydb`.`CBGV` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NGHIENCUUSINH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NGHIENCUUSINH` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hoten` VARCHAR(45) NULL,
  `hinhthuchuongdan` VARCHAR(45) NULL,
  `donvicongtac` VARCHAR(45) NULL,
  `nambaovethanhcong` DATETIME NULL,
  `CBGV_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_NGHIENCUUSINH_CBGV1_idx` (`CBGV_id` ASC) VISIBLE,
  CONSTRAINT `fk_NGHIENCUUSINH_CBGV1`
    FOREIGN KEY (`CBGV_id`)
    REFERENCES `mydb`.`CBGV` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TRINHDONN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TRINHDONN` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tenngoaingu` VARCHAR(45) NULL,
  `nghe` VARCHAR(45) NULL,
  `noi` VARCHAR(45) NULL,
  `doc` VARCHAR(45) NULL,
  `viet` VARCHAR(45) NULL,
  `CBGV_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TRINHDONN_CBGV1_idx` (`CBGV_id` ASC) VISIBLE,
  CONSTRAINT `fk_TRINHDONN_CBGV1`
    FOREIGN KEY (`CBGV_id`)
    REFERENCES `mydb`.`CBGV` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QUATRINHCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`QUATRINHCT` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `thoigian` VARCHAR(45) NULL,
  `vitricongtac` VARCHAR(45) NULL,
  `linhvucEntity` VARCHAR(45) NULL,
  `coquancongtac` VARCHAR(45) NULL,
  `CBGV_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_QUATRINHCT_CBGV1_idx` (`CBGV_id` ASC) VISIBLE,
  CONSTRAINT `fk_QUATRINHCT_CBGV1`
    FOREIGN KEY (`CBGV_id`)
    REFERENCES `mydb`.`CBGV` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QUATRINHDT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`QUATRINHDT` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bacdaotao` VARCHAR(45) NULL,
  `noidaotao` VARCHAR(45) NULL,
  `chuyennghanh` VARCHAR(45) NULL,
  `namtotnghiep` DATETIME NULL,
  `CBGV_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_QUATRINHDT_CBGV1_idx` (`CBGV_id` ASC) VISIBLE,
  CONSTRAINT `fk_QUATRINHDT_CBGV1`
    FOREIGN KEY (`CBGV_id`)
    REFERENCES `mydb`.`CBGV` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DETAIKHCNGANDAY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DETAIKHCNGANDAY` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tenduan` VARCHAR(45) NULL,
  `chutrithamgia` VARCHAR(45) NULL,
  `thoigian` VARCHAR(45) NULL,
  `thuocchuongtrinh` VARCHAR(45) NULL,
  `tinhtrang` VARCHAR(45) NULL,
  `CBGV_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DETAIKHCNGANDAY_CBGV1_idx` (`CBGV_id` ASC) VISIBLE,
  CONSTRAINT `fk_DETAIKHCNGANDAY_CBGV1`
    FOREIGN KEY (`CBGV_id`)
    REFERENCES `mydb`.`CBGV` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DANHMUCCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DANHMUCCT` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tapchiquocte` VARCHAR(45) NULL,
  `tapchiquocgia` VARCHAR(45) NULL,
  `hoinghiquocte` VARCHAR(45) NULL,
  `hoinghiquocgia` VARCHAR(45) NULL,
  `sachchuyenkhao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CBGV_CT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CBGV_CT` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tencongtrinh` VARCHAR(45) NULL,
  `tacgia` VARCHAR(45) NULL,
  `noicongbo` VARCHAR(45) NULL,
  `CBGV_CTcol` VARCHAR(45) NULL,
  `CBGV_id` INT NULL,
  `DANHMUCCT_id` INT NULL,
  INDEX `fk_CBGV_CT_CBGV1_idx` (`CBGV_id` ASC) VISIBLE,
  INDEX `fk_CBGV_CT_DANHMUCCT1_idx` (`DANHMUCCT_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_CBGV_CT_CBGV1`
    FOREIGN KEY (`CBGV_id`)
    REFERENCES `mydb`.`CBGV` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CBGV_CT_DANHMUCCT1`
    FOREIGN KEY (`DANHMUCCT_id`)
    REFERENCES `mydb`.`DANHMUCCT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DANHMUCVB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DANHMUCVB` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `docquyensangche` VARCHAR(45) NULL,
  `giaiphaphuuich` VARCHAR(45) NULL,
  `vanbangbaohoGCT` VARCHAR(45) NULL,
  `TKBTMTH` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CBGV_VB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CBGV_VB` (
  `id` VARCHAR(45) NOT NULL,
  `tennoidung` VARCHAR(45) NULL,
  `namcap` DATETIME NULL,
  `CBGV_id` INT NULL,
  `DANHMUCVB_id` INT NULL,
  INDEX `fk_CBGV_VB_DANHMUCVB1_idx` (`DANHMUCVB_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_CBGV_VB_CBGV1`
    FOREIGN KEY (`CBGV_id`)
    REFERENCES `mydb`.`CBGV` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CBGV_VB_DANHMUCVB1`
    FOREIGN KEY (`DANHMUCVB_id`)
    REFERENCES `mydb`.`DANHMUCVB` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GIAITHUONG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GIAITHUONG` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hinhthucnoidung` VARCHAR(45) NULL,
  `namtangthuong` VARCHAR(45) NULL,
  `DANHMUCCT_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_GIAITHUONG_DANHMUCCT1_idx` (`DANHMUCCT_id` ASC) VISIBLE,
  CONSTRAINT `fk_GIAITHUONG_DANHMUCCT1`
    FOREIGN KEY (`DANHMUCCT_id`)
    REFERENCES `mydb`.`DANHMUCCT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CTADTHUCTIEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CTADTHUCTIEN` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ten_cong_trinh` VARCHAR(100) NULL,
  `hinh_thuc_quy_mo` VARCHAR(45) NULL,
  `thoi_gian` DATETIME NULL,
  `DANHMUCCT_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CTADTHUCTIEN_DANHMUCCT1_idx` (`DANHMUCCT_id` ASC) VISIBLE,
  CONSTRAINT `fk_CTADTHUCTIEN_DANHMUCCT1`
    FOREIGN KEY (`DANHMUCCT_id`)
    REFERENCES `mydb`.`DANHMUCCT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roleEntity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roleEntity` (
  `roleid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`roleid`))
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


alter table cbgvEntity add column roleid int;
alter table cbgvEntity add constraint fk_cbgv_role foreign key (roleid) references roleEntity(roleid);
